name: Build-and-test
on: push

env:
  SOURCE_DIR: ${{ github.workspace }}
  QT_VERSION: 6.8.2
  QT_ARCH: "win64_mingw"
  BUILD_TYPE: Debug
  ARTIFACT_WITHOUT_ZIP_ENDING: GovnoChatClient
  BUILD_DIR_NAME: buildGovnoChatClient
  

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Qt
        id: install-qt
        uses: jurplel/install-qt-action@v4
        with:
          aqtversion: '==3.1.*'
          version: ${{ env.QT_VERSION }}
          host: "windows"
          target: desktop
          arch: ${{ env.QT_ARCH }}
          dir: ${{ runner.temp }}
          tools: 'tools_cmake tools_ninja'
          archives: 'MinGW'
          # cache: true

      - name: Set up environment variables
        shell: pwsh
        run: |
          $qtDir = "${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/bin"
          Write-Host "Adding Qt bin directory to PATH: $qtDir"
          $env:PATH += ";$qtDir"
          Write-Host "PATH: $($env:PATH)"
          dir ${{ runner.temp }}/Qt/${{ env.QT_VERSION }}/mingw_64

      - name: Configure CMake
        run: |
          cmake -G "MinGW Makefiles" -B ${{ runner.temp }}\${{ env.BUILD_DIR_NAME }} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_PREFIX_PATH="$env:QtDir"

      - name: Build
        run: |
          cd ${{ runner.temp }}\${{ env.BUILD_DIR_NAME }}
          mingw32-make -j6 


